#!/bin/bash
# Build Freon Linux packages from source.
# Version: 0.0.1
# (C) Chris Dorman, 2018 GPLv3+

#### Variables ###
# mirrors
tccmirror="http://download.savannah.gnu.org/releases/tinycc"

# filenames
tccsrcfile="tcc-0.9.27.tar.bz2"

# folders
tccsrcdir=${tccsrcfile//.tar.bz2}

# Build simple C toolchain for Freon Linux (tcc)

if [ ! -d "pkgsrc" ]; then
  echo "Warning: package source directory not found, creating."
  mkdir pkgsrc > /dev/null 2>&1
fi

cd pkgsrc

tcc()
{
	# build specific vars
	getfile="$tccmirror/$tccsrcfile"

	# Downloading TCC source
	if [ ! -f "$tccsrcfile" ]; then
		echo "Downloading TCC sources..."
		wget $getfile
		tar -xf $tccsrcfile
	fi

	# Make location for build
	mkdir ../pkgs/tcc

	# Configure TCC
	cd $tccsrcdir
	./configure --prefix=`pwd`/../../pkgs/tcc

	# Compile
	make -j20

	# Copy
	make install

	sleep 2

	# Compress
	../../deps/mkpak `pwd`/../../pkgs tcc

	sleep 2

	# Clean
	rm -r ../../pkgsrc
	rm -r ../../pkgs/tcc

	echo "Done!"
}

case $1 in
	* ) echo "Building $1..."
		$1;;
esac
