#!/bin/bash
# Build Freon Linux software from source.
# Version: 0.1.0
# (C) Chris Dorman, 2018 GPLv3+

#### Variables ###
# mirrors
tccmirror="http://download.savannah.gnu.org/releases/tinycc"
nanomirror="https://www.nano-editor.org/dist/v3"
chttpdmirror="https://github.com/Pentium44/chttpd.git"
ftpmirror="https://github.com/Harlonxl/minFTPD.git"
ncursesmirror="https://ftp.gnu.org/pub/gnu/ncurses"
bashmirror="https://ftp.gnu.org/gnu/bash"
zlibmirror="https://zlib.net"
termcapmirror="https://ftp.gnu.org/gnu/termcap"
dropbearmirror="https://matt.ucc.asn.au/dropbear/releases"
htopmirror="https://hisham.hm/htop/releases/2.2.0"

# filenames
tcc="tcc-0.9.27.tar.bz2"
nano="nano-3.1.tar.xz"
ncurses="ncurses-6.1.tar.gz"
bash="bash-5.0.tar.gz"
zlib="zlib-1.2.11.tar.xz"
termcap="termcap-1.3.1.tar.gz"
dropbear="dropbear-2019.78.tar.bz2"
htop="htop-2.2.0.tar.gz"

# folders
tmpdir="`pwd`/pkgsrc"
softwaredir="`pwd`/src/rootfs"
tccsrcdir=${tcc//.tar.bz2}
nanosrcdir=${nano//.tar.xz}
ncursessrcdir=${ncurses//.tar.gz}
bashsrcdir=${bash//.tar.gz}
zlibsrcdir=${zlib//.tar.xz}
termcapsrcdir=${termcap//.tar.gz}
dropbearsrcdir=${dropbear//.tar.bz2}
htopsrcdir=${htop//.tar.gz}

# Build simple C toolchain for Freon Linux (tcc)

if [ ! -d "$tmpdir" ]; then
  echo "Warning: package source directory not found, creating."
  mkdir $tmpdir > /dev/null 2>&1
fi

cd $tmpdir

bash()
{
	# Downloading TCC source
        if [ ! -f "$bash" ]; then
                echo "Downloading bash sources..."
                wget $bashmirror/$bash
                tar -xf $bash
        fi

	cd $bashsrcdir
        ./configure --prefix=$softwaredir \
        --without-bash-malloc
        make -j20
        make install
	cd ..
}

tcc()
{
	# Downloading TCC source
	if [ ! -f "$tcc" ]; then
		echo "Downloading TCC sources..."
		wget $tccmirror/$tcc
		tar -xf $tcc
	fi

	# Configure TCC
	cd $tccsrcdir
	./configure --prefix=$softwaredir

	# Compile
	make -j20
	make install
	cd ..
	sleep 2
}

htop()
{
        # Downloading TCC source
        if [ ! -f "$htop" ]; then
                echo "Downloading TCC sources..."
                wget $htopmirror/$htop
                tar -xf $htop
        fi

        # Configure TCC
        cd $htopsrcdir
        ./configure --prefix=$softwaredir

        # Compile
        make -j20
        make install
        cd ..
}

dropbear()
{
        # Downloading dropbear source
        if [ ! -f "$dropbear" ]; then
                echo "Downloading Dropbear sources..."
                wget $dropbearmirror/$dropbear
                tar -xf $dropbear
        fi

        # Configure dropbear
        cd $dropbearsrcdir

	cp -v options.h options.h.backup
	sed -e "s@/dev/random@/dev/urandom@" options.h.backup > options.h
	./configure --prefix=$softwaredir

        # Compile
        make PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" MULTI=1
        make MULTI=1 PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" install

        mkdir -pv $softwaredir/etc/dropbear
	rm $softwaredir/sbin/dropbear
	rm $softwaredir/bin/{dropbearconvert,dropbearkey,scp,dbclient}

	cd $softwaredir/bin

	ln -svf dropbearmulti dropbear
	ln -svf dropbearmulti dbclient
	ln -svf dropbearmulti dropbearkey
	ln -svf dropbearmulti dropbearconvert
	ln -svf dropbearmulti scp

        cd $tmpdir
}

termcap()
{
	# Downloading termcap source
        if [ ! -f "$termcap" ]; then
                echo "Downloading termcap sources..."
                wget $termcapmirror/$termcap
                tar -xf $termcap
        fi

        # Configure TCC
        cd $termcapsrcdir
        ./configure --prefix=$softwaredir --with-shared --without-normal 

        # Compile
        make -j20
        make install
        cd ..

}

nano()
{
	# Downloading nano source
	if [ ! -f "$nano" ]; then
		echo "Downloading nano editor sources..."
		wget $nanomirror/$nano
		tar -xf $nano
	fi

	# Confingure
	cd $nanosrcdir
	./configure --prefix=$softwaredir

	# Compile
	make -j20
	make install
	cd ..
}

ncurses()
{
	# Downloading nano source
        if [ ! -f "$ncurses" ]; then
                echo "Downloading ncurses sources..."
                wget $ncursesmirror/$ncurses
                tar -xf $ncurses
        fi

	# Configure
	cd $ncursessrcdir
	./configure --prefix=$softwaredir \
		--with-shared \
		--without-debug \
		--without-normal \
		--enable-widec 

	# Compile
	make -j20
	make install

	make distclean
	./configure --prefix=/usr    \
            --with-shared    \
            --without-normal \
            --without-debug  \
            --without-cxx-binding \
            --with-abi-version=5 \
	    --with-versioned-syms

	make sources libs
	cp -av lib/lib*.so.5* ../../src/rootfs/lib

	cd ../../src/rootfs/lib

	ln -s libncurses.so.6 libtinfo.so.6
	ln -s libtinfo.so.6 libtinfo.so

	ln -s libncurses.so.5 libtinfo.so.5 
        ln -s libtinfo.so.5 libtinfo.so

        ln -s libncursesw.so.6 libncursesw.so.5

	cd ../../../pkgsrc
}

zlib()
{
        # Downloading zlib source
        if [ ! -f "$zlib" ]; then
                echo "Downloading zlib sources..."
                wget $zlibmirror/$zlib
                tar -xf $zlib
        fi

        # Confingure
        cd $zlibsrcdir
        ./configure --prefix=$softwaredir

        # Compile
        make -j20
        make install

	# mv -v ../../src/rootfs/usr/lib/libz.so.* ../../src/rootfs/lib
	# ln -sfv ../../src/rootfs/lib/libz.so ../../src/rootfs/usr/lib/libz.so

        cd ..
}


chttpd()
{
	if [ ! -d "chttpd" ]; then
		git clone $chttpdmirror
	fi

	cd chttpd
	make -j20

        cp chttpd ../../src/rootfs/sbin/
	cp inc/chttpd.conf ../../src/rootfs/etc
	cp inc/chttpd ../../src/rootfs/etc/init.d
	cd ..
}

ftp()
{
        if [ ! -d "minFTPD" ]; then
                git clone $ftpmirror
        fi

        cd minFTPD
        make -j20

        cp minFTPD ../../src/rootfs/sbin/
	cp miniFTPD.conf ../../src/rootfs/etc/

}


case $1 in
	all ) echo "Building all!"
		ncurses; nano; chttpd; tcc; bash; termcap; zlib; dropbear; cd $tmpdir/../;;
	* ) echo "Building $1..."
		$1;;
esac
